# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Out of Oblivion'
description: "Random thoughts and findings of a novice coder."

# Author's info
author: 'Arka Prava Basu'
# edit 'categories' in the front matter of every post to match this username
nickname: archie94
bio: 'CS Undergraduate from NIT Durgapur. Android Developer and technophile.'
location: 'West Bengal, India'
url: 'http://archie94.github.io/blogs/'
image: 'assets/images/arka.jpg'

short_url: 'archie94.github.io/blogs/'
google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /blogs/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: archie94
repo: blogs
branch: gh-pages
relative_source: ../blogs/
destination: ../blogs-pages/
production_url:  https://archie94.github.io/blogs/
source_url:      https://github.com/archie94/blogs/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
